# Generated by Django 3.0.6 on 2020-05-12 05:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=255)),
                ('is_closed', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=255)),
                ('review_count', models.IntegerField()),
                ('rating', models.FloatField()),
                ('price', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=11)),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
                ('page_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_type', to='api.PageType')),
            ],
        ),
        migrations.RemoveField(
            model_name='businessattributes',
            name='business',
        ),
        migrations.RemoveField(
            model_name='businessattributes',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='businessattributes',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='businessattributes',
            name='location',
        ),
        migrations.RemoveField(
            model_name='businessattributes',
            name='transactions',
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='display_address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='BusinessAttributes',
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.DeleteModel(
            name='DisplayAddress',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate_type', to='api.PageType'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='page_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type', to='api.PageType'),
        ),
        migrations.AddField(
            model_name='category',
            name='page_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_type', to='api.PageType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='page_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_type', to='api.PageType'),
            preserve_default=False,
        ),
    ]
