# Generated by Django 3.0.6 on 2020-05-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200512_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='display_address',
            field=models.TextField(blank=True),
        ),
    ]
